// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9AEEcIyMTrzzNnT8rh2SuMixzrfhv1dY',
    appId: '1:535447433469:web:03f750d41a554fd86d4e94',
    messagingSenderId: '535447433469',
    projectId: 'flutter-auth-264b2',
    authDomain: 'flutter-auth-264b2.firebaseapp.com',
    storageBucket: 'flutter-auth-264b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2BVZAVU_0W7izVjvQYC0MN30UPjEFOi4',
    appId: '1:535447433469:android:707e9482f2e502ff6d4e94',
    messagingSenderId: '535447433469',
    projectId: 'flutter-auth-264b2',
    storageBucket: 'flutter-auth-264b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPbXmv2_HNt2HlMGKWY5HyS3Hz1qccOaI',
    appId: '1:535447433469:ios:a9fe984c676a644a6d4e94',
    messagingSenderId: '535447433469',
    projectId: 'flutter-auth-264b2',
    storageBucket: 'flutter-auth-264b2.appspot.com',
    iosClientId: '535447433469-h0ngovvoimbf7mgm07q87mn0fpakeojk.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPbXmv2_HNt2HlMGKWY5HyS3Hz1qccOaI',
    appId: '1:535447433469:ios:a9fe984c676a644a6d4e94',
    messagingSenderId: '535447433469',
    projectId: 'flutter-auth-264b2',
    storageBucket: 'flutter-auth-264b2.appspot.com',
    iosClientId: '535447433469-h0ngovvoimbf7mgm07q87mn0fpakeojk.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );
}
